#!/usr/bin/env bash

#/**
# * PhpStorm URL Handler
# *
# * phpstorm://open?url=file://@file&line=@line
# * phpstorm://open?file=@file&line=@line
# *
# * @license GPL3
# * @author  Stefan Auditor <stefan.auditor@erdfisch.de>
# */

argument=${1}
pattern=".*file(:\/\/|\=)(.*)&line=(.*)"

# Get the file path.
file=$(echo "${argument}" | sed -r "s/${pattern}/\2/")

# Get the line number.
line=$(echo "${argument}" | sed -r "s/${pattern}/\3/")

# Check if phpstorm|pstorm command exist.
if [ -n "$(command -v phpstorm)" ]; then
    /usr/bin/env phpstorm --line "${line}" "${file}"
elif [ -n "$(command -v pstorm)" ]; then
    /usr/bin/env pstorm --line "${line}" "${file}"
fi
